services:
    primehalo.primeloginreturn.listener:
        class: primehalo\primeloginreturn\event\listener
        arguments:
            - @template
            - @user
            - '%core.root_path%'
            - '%core.php_ext%'
        tags:
            - { name: event.listener }